// Package llm is the thin LLM-client seam the librarian's tool-call loop drives.
//
// It defines provider-neutral message/block/tool types plus a single
// round-trip Client interface (CreateMessage) so the loop is provider-agnostic
// without being over-abstracted. The only concrete implementation today is the
// Anthropic client (see anthropic.go), which — by swapping nothing but the base
// URL, key, and model — serves BOTH the live Anthropic API and a local ollama
// instance via ollama's Anthropic-compatible /v1/messages endpoint. LIVE and
// DEBUG are one code path.
package llm

import (
	"context"
	"encoding/json"
	"fmt"
)

// Role is the conversational role of a message.
type Role string

const (
	// RoleUser is a message authored by the caller (the question, and the
	// tool_result blocks fed back into the loop).
	RoleUser Role = "user"
	// RoleAssistant is a message generated by the model (text and/or tool_use
	// blocks).
	RoleAssistant Role = "assistant"
)

// Block kinds. These mirror the three content-block shapes the read-only
// tool-call loop needs; thinking/citation/other blocks are intentionally not
// modelled (the librarian does not use them — design report §3.2).
const (
	BlockText       = "text"
	BlockToolUse    = "tool_use"
	BlockToolResult = "tool_result"
)

// Block is one content block within a Message. Which fields are meaningful
// depends on Type:
//
//   - BlockText:       Text
//   - BlockToolUse:    ID, Name, Input          (model asks to call a tool)
//   - BlockToolResult: ToolUseID, Content, IsError (loop feeds a result back)
type Block struct {
	Type string

	// Text — BlockText.
	Text string

	// ID, Name, Input — BlockToolUse. Input is the raw JSON arguments the
	// model produced for the tool call.
	ID    string
	Name  string
	Input json.RawMessage

	// ToolUseID, Content, IsError — BlockToolResult. ToolUseID references the
	// originating tool_use block's ID.
	ToolUseID string
	Content   string
	IsError   bool
}

// Message is one turn in the conversation.
type Message struct {
	Role    Role
	Content []Block
}

// ToolDef is a tool definition handed to the model. Properties and Required
// together form the tool's JSON-schema input shape (an object schema). The
// constraint guard — not the schema — is what actually enforces safety; the
// schema only shapes the arguments the model produces.
type ToolDef struct {
	Name        string
	Description string
	Properties  map[string]any
	Required    []string
}

// CreateMessageParams is one round-trip's worth of input: the system prompt,
// the running message list, and the available tool definitions.
type CreateMessageParams struct {
	System   string
	Messages []Message
	Tools    []ToolDef
}

// Client is the seam the tool-call loop drives. One implementation (Anthropic)
// exists today; the interface stays thin enough that another provider could be
// slotted later without touching the loop.
type Client interface {
	// CreateMessage performs one model round-trip and returns the assistant's
	// reply (either tool_use blocks to dispatch, or a final text answer).
	CreateMessage(ctx context.Context, params CreateMessageParams) (Message, error)
}

// Provider names accepted by NewClient.
const (
	ProviderAnthropic = "anthropic"
	ProviderOpenAI    = "openai"
	ProviderGemini    = "gemini"
)

// LLMConfig configures the LLM client. The provider selects the SDK; the model
// is required (the SDKs have no model env var); BaseURL is optional (omitted ⇒
// the SDK's production endpoint; set only for ollama/proxy).
//
// The API key is DELIBERATELY absent: secrets do not belong in config. Each SDK
// auto-reads its key from the environment — ANTHROPIC_API_KEY for the anthropic
// provider, OPENAI_API_KEY for the openai provider, GEMINI_API_KEY or
// GOOGLE_API_KEY for the gemini provider (for ollama debugging the env key is the
// ignored placeholder "ollama"). Shoka never reads or handles the key.
//
//	prod (anthropic):  {Provider:"anthropic", Model:"claude-…"}                              + ANTHROPIC_API_KEY in env
//	prod (openai):     {Provider:"openai",    Model:"gpt-…"}                                 + OPENAI_API_KEY in env
//	prod (gemini):     {Provider:"gemini",    Model:"gemini-…"}                              + GEMINI_API_KEY (or GOOGLE_API_KEY) in env
//	debug (ollama):    {Provider:"anthropic", BaseURL:"http://localhost:11434", Model:"…"}   + ANTHROPIC_API_KEY=ollama
type LLMConfig struct {
	Provider string // "anthropic" | "openai" | "gemini"
	BaseURL  string // "" => SDK production default; "http://localhost:11434" => local ollama
	Model    string // required; "claude-…" / "gpt-…" / an ollama tag
	MaxSteps int    // tool-call loop budget (max model round-trips)
}

// IsConfigured reports whether the librarian should be enabled: a provider and a
// model. Whether the env key is present/valid is what the health-check verifies
// (see health.go) — not this gate.
func (c LLMConfig) IsConfigured() bool {
	return c.Provider != "" && c.Model != ""
}

// NewClient builds the LLM client for the configured provider. An unknown
// provider is a clear error, never a silent fallback. Neither client is given
// an explicit key option — the SDK reads its key from the environment.
func NewClient(cfg LLMConfig) (Client, error) {
	switch cfg.Provider {
	case ProviderAnthropic:
		return newAnthropicClient(cfg), nil
	case ProviderOpenAI:
		return newOpenAIClient(cfg), nil
	case ProviderGemini:
		return newGeminiClient(cfg), nil
	default:
		return nil, fmt.Errorf("unknown llm provider %q (want %q, %q or %q)", cfg.Provider, ProviderAnthropic, ProviderOpenAI, ProviderGemini)
	}
}

// EmbeddingVector is the result of an embedding call.
type EmbeddingVector struct {
	Model      string
	Dimensions int
	Values     []float64
}

// Embedder produces embedding vectors from text via an LLM provider.
type Embedder interface {
	Embed(ctx context.Context, text string) (*EmbeddingVector, error)
}

// NewEmbedder builds an Embedder for the configured provider.
func NewEmbedder(cfg LLMConfig) (Embedder, error) {
	switch cfg.Provider {
	case ProviderOpenAI:
		return newOpenAIEmbedder(cfg), nil
	case ProviderGemini:
		return newGeminiEmbedder(cfg), nil
	case ProviderAnthropic:
		return nil, fmt.Errorf("provider %q does not support embeddings", ProviderAnthropic)
	default:
		return nil, fmt.Errorf("unknown llm provider %q (want %q, %q or %q)", cfg.Provider, ProviderAnthropic, ProviderOpenAI, ProviderGemini)
	}
}
