// Package llm is the thin LLM-client seam the librarian's tool-call loop drives.
//
// It defines provider-neutral message/block/tool types plus a single
// round-trip Client interface (CreateMessage) so the loop is provider-agnostic
// without being over-abstracted. The only concrete implementation today is the
// Anthropic client (see anthropic.go), which — by swapping nothing but the base
// URL, key, and model — serves BOTH the live Anthropic API and a local ollama
// instance via ollama's Anthropic-compatible /v1/messages endpoint. LIVE and
// DEBUG are one code path.
package llm

import (
	"context"
	"encoding/json"
)

// Role is the conversational role of a message.
type Role string

const (
	// RoleUser is a message authored by the caller (the question, and the
	// tool_result blocks fed back into the loop).
	RoleUser Role = "user"
	// RoleAssistant is a message generated by the model (text and/or tool_use
	// blocks).
	RoleAssistant Role = "assistant"
)

// Block kinds. These mirror the three content-block shapes the read-only
// tool-call loop needs; thinking/citation/other blocks are intentionally not
// modelled (the librarian does not use them — design report §3.2).
const (
	BlockText       = "text"
	BlockToolUse    = "tool_use"
	BlockToolResult = "tool_result"
)

// Block is one content block within a Message. Which fields are meaningful
// depends on Type:
//
//   - BlockText:       Text
//   - BlockToolUse:    ID, Name, Input          (model asks to call a tool)
//   - BlockToolResult: ToolUseID, Content, IsError (loop feeds a result back)
type Block struct {
	Type string

	// Text — BlockText.
	Text string

	// ID, Name, Input — BlockToolUse. Input is the raw JSON arguments the
	// model produced for the tool call.
	ID    string
	Name  string
	Input json.RawMessage

	// ToolUseID, Content, IsError — BlockToolResult. ToolUseID references the
	// originating tool_use block's ID.
	ToolUseID string
	Content   string
	IsError   bool
}

// Message is one turn in the conversation.
type Message struct {
	Role    Role
	Content []Block
}

// ToolDef is a tool definition handed to the model. Properties and Required
// together form the tool's JSON-schema input shape (an object schema). The
// constraint guard — not the schema — is what actually enforces safety; the
// schema only shapes the arguments the model produces.
type ToolDef struct {
	Name        string
	Description string
	Properties  map[string]any
	Required    []string
}

// CreateMessageParams is one round-trip's worth of input: the system prompt,
// the running message list, and the available tool definitions.
type CreateMessageParams struct {
	System   string
	Messages []Message
	Tools    []ToolDef
}

// Client is the seam the tool-call loop drives. One implementation (Anthropic)
// exists today; the interface stays thin enough that another provider could be
// slotted later without touching the loop.
type Client interface {
	// CreateMessage performs one model round-trip and returns the assistant's
	// reply (either tool_use blocks to dispatch, or a final text answer).
	CreateMessage(ctx context.Context, params CreateMessageParams) (Message, error)
}

// LLMConfig configures the LLM client. The same struct selects live Anthropic
// and local-ollama debugging — they differ only in BaseURL, APIKey, and Model:
//
//	live:  {Provider:"anthropic", BaseURL:"",                       APIKey:<real>,    Model:"claude-…"}
//	debug: {Provider:"anthropic", BaseURL:"http://localhost:11434", APIKey:"ollama",  Model:"Qwen3:1.7b-q4_K_M"}
type LLMConfig struct {
	Provider string // "anthropic"
	BaseURL  string // "" => real Anthropic; "http://localhost:11434" => local ollama
	APIKey   string // real key live; "ollama" (accepted-but-ignored) for local
	Model    string // "claude-…" live; "Qwen3:1.7b-q4_K_M" debug
	MaxSteps int    // tool-call loop budget (max model round-trips)
}

// IsConfigured reports whether the config carries enough to build a client: a
// provider, a model, and a credential (a real key, or the ollama placeholder
// that rides on a base-URL override).
func (c LLMConfig) IsConfigured() bool {
	return c.Provider != "" && c.Model != "" && c.APIKey != ""
}
