FROM mcr.microsoft.com/devcontainers/go:1.22-bookworm

# Install additional OS packages if needed
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

EXPOSE 8080 8081
