#!/usr/bin/env bash
# Generate a LOCAL test CA and a server certificate for the B-61 OAuth e2e harness.
#
# This is a TEST-ONLY certificate authority. The CA key never leaves this directory
# and is git-ignored. The leaf cert covers the two placeholder hostnames the harness
# uses on its private Docker network:
#   - shoka.test   : the public origin clients connect to (Apache reverse-proxies it)
#   - client.test  : where the client's CIMD metadata document is served (Apache vhost)
#
# Nothing here is an operator secret: placeholder hostnames + a freshly generated
# local CA only. Re-run is idempotent-ish: it regenerates if files are missing.
set -euo pipefail
cd "$(dirname "$0")"

# Ensure the generated key/cert material is never committed (the directive forbids
# secrets in committed artefacts; these are throwaway local-test material anyway).
ignore_file=".gitignore"
if [[ ! -f "$ignore_file" ]]; then
  printf '%s\n' '# Generated by gen-certs.sh — never commit the test CA key/certs.' '*.key' '*.crt' '*.srl' '*.csr' > "$ignore_file"
fi

if [[ -f ca.crt && -f server.crt && -f server.key ]]; then
  echo "certs already present (ca.crt, server.crt, server.key) — skipping generation"
  exit 0
fi

echo "generating local test CA + server cert for shoka.test / client.test ..."

# 1. Local CA.
openssl genrsa -out ca.key 4096 >/dev/null 2>&1
openssl req -x509 -new -nodes -key ca.key -sha256 -days 825 \
  -subj "/CN=Shoka B-61 E2E Test CA" \
  -out ca.crt >/dev/null 2>&1

# 2. Server key + CSR.
openssl genrsa -out server.key 2048 >/dev/null 2>&1
openssl req -new -key server.key \
  -subj "/CN=shoka.test" \
  -out server.csr >/dev/null 2>&1

# 3. Sign the leaf with SANs for both placeholder hostnames.
cat > server.ext <<'EOF'
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = shoka.test
DNS.2 = client.test
EOF

openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
  -out server.crt -days 825 -sha256 -extfile server.ext >/dev/null 2>&1

rm -f server.csr server.ext ca.srl
echo "done: ca.crt, server.crt, server.key"
